name: Main Build

on:
    workflow_dispatch:
    pull_request:
        branches: [main]
env:
  GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
  GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}

jobs:
    build-push-wrapping-artefacts:
        name: Building and Deploying Maven artefcats
        runs-on: ubuntu-latest

        steps:
          - name: Checkin Code
            uses: actions/checkout@v4
          
          - name: Set up JDK 11
            uses: actions/setup-java@v4
            with:
              java-version: '11'
              distribution: 'temurin'
              server-id: 'github'
              server-username: GITHUB_ACTOR
              server-password: GITHUB_TOKEN
              settings-path: '~/.m2'
              gpg-private-key: ${{secrets.GPG_PRIVATE_KEY}}
              gpg-passphrase: GPG_PASSPHRASE
              cache: maven
          
          - name: Import GPG key
            run: |
                mkdir -p ~/.gnupg
                echo "use-agent" > ~/.gnupg/gpg.conf
                echo "pinentry-mode loopback" > ~/.gnupg/gpg.conf
                echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
            env:
                GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      
          - name: List GPG keys
            run: gpg --list-secret-keys --keyid-format LONG
      
          - name: Configure default GPG key
            run: |
                KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | awk -F '/' '{print $2}')
                gpg --batch --yes --pinentry-mode loopback --passphrase ${{ secrets.GPG_PASSPHRASE }} --quick-set-expire $KEY_ID 0
                gpg --batch --yes --pinentry-mode loopback --passphrase ${{ secrets.GPG_PASSPHRASE }} --quick-sign-key $KEY_ID default
                gpg --batch --yes --pinentry-mode loopback --passphrase ${{ secrets.GPG_PASSPHRASE }} --quick-lsign-key $KEY_ID default
      

          - name: Building artefacts
            env:
              GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
              GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
              GITHUB_ACTOR: ${{github.actor}}
              GITHUB_TOKEN: ${{github.token}}
            run: |
             mvn -X --batch-mode -Dgpg.passphrase=GPG_PASSPHRASE deploy \
             -Dgpg.keyname=jaydee029
             -Dgalasa.source.repo=https://repo.maven.apache.org/maven2/ \
             -Dgalasa.central.repo=https://repo.maven.apache.org/maven2/   \
             -Dgalasa.release.repo=https://maven.pkg.github.com/jaydee029/wrapping        \
             -Dgalasa.jacocoEnabled=true -Dgalasa.isRelease=true 
            
    